repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.8
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
        files: ^((nad_serial|scripts|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.3
    hooks:
      - id: codespell
        exclude_types: [pdf]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --indent, "\t", --no-ensure-ascii]
  - repo: local
    hooks:
      # Run mypy through our wrapper script in order to get the possible
      # pyenv and/or virtualenv activated; it may not have been e.g. if
      # committing from a GUI tool that was not launched from an activated
      # shell.
      #- id: mypy
      #  name: mypy
      #  entry: script/run-in-env.sh mypy
      #  language: script
      #  require_serial: true
      #  types: [python]
      #  files: ^(nad_serial)/.+\.py$
      - id: pylint
        name: pylint
        entry: script/run-in-env.sh pylint
        language: script
        require_serial: true
        types: [python]
        files: ^(nad_serial|tests)/.+\.py$
